### ISSUE TITLE
Color calibration to be available

### ISSUE THREAD

**Issue by es20490446e** [linuxdeepin/dde-api#2]
It would be nice if ColorD and ArgyllCMS worked in Deepin, thus allowing color calibrations tools to function.

**Comment by es20490446e** [comment]
I have also opened a [report](https://hub.displaycal.net/forums/topic/color-calibration-on-deepin/) at the DisplayCAL project.

**Comment by es20490446e** [comment]
Actually the only thing that is required is installing xiccd and enabling it on boot. As specimen the following [script](https://goo.gl/6Sbmt2) fixes it in Arch.

**Comment by jouyouyun** [comment]
You can install xiccd manually, and use system service to enable it on boot, or autostaart mechanism.

**Comment by es20490446e** [comment]
I have made a [request](https://github.com/agalakhov/xiccd/issues/15) for xiccd to be auto-started by default.

**Comment by jouyouyun** [comment]
Great!
