### ISSUE TITLE
Build error on go-gir-generator

### ISSUE THREAD

**Issue by hillwoodroc** [linuxdeepin/dde-api#26]
[   64s] cd /home/abuild/rpmbuild/BUILD/go/src/pkg.deepin.io/dde/api/powersupply
[   64s] /usr/lib64/go/1.14/pkg/tool/linux_amd64/compile -o $WORK/b230/_pkg_.a -trimpath "$WORK/b230=>" -shared -p pkg.deepin.io/dde/api/powersupply -complete -installsuffix shared -buildid EMTK6a6E1jyTiQK4WDgC/EMTK6a6E1jyTiQK4WDgC -goversion go1.14.15 -D "" -importcfg $WORK/b230/importcfg -pack ./powersupply.go
[   64s] # pkg.deepin.io/gir/gio-2.0
[   64s] ../contrib/src/pkg.deepin.io/gir/gio-2.0/gio.go:1504:40: undefined: glib.Source
[   64s] ../contrib/src/pkg.deepin.io/gir/gio-2.0/gio.go:1510:12: undefined: glib.Source
[   64s] ../contrib/src/pkg.deepin.io/gir/gio-2.0/gio.go:1513:11: undefined: glib.Source

**Comment by cheese** [comment]
https://github.com/linuxdeepin/go-gir-generator/pull/11
