### ISSUE TITLE
Deepin-api causes deepin-control-center hang

### ISSUE THREAD

**Issue by mozzi-arch** [linuxdeepin/dde-api#3]
deepin-api  has been updated to 3.1.20-1 and causes deepin-control-center hang.
Workaround : after upgrade to version 3.1.20-1 of deepin-api, when I click on control center, my system is freezing and blocked. 
I must restart by ALT+CTRL+F2 and reboot

**Comment by carlocastoldi** [comment]
same problem here. In addition i can't right click on any icon on the dock

**Comment by felixonmars** [comment]
Please try again with dtkwidget 2.0.6-2 and deepin-qt-dbus-factory 0.4.2-2.

**Comment by carlocastoldi** [comment]
that fixed the control center and the right-click-menu making the system freeze and block.
On the other hand now if i right click on the icons on the dock nothing happens... any idea?

**Comment by carlocastoldi** [comment]
updating deepin-menu fixed it 👍 
Now the last problem introduced in the last few days is that when opening a terminal with keyboard shortcut it no longer show up in front of any other window.
That doesn't happen with other shortcuts (File Explorer, deepin Monitor,..)

**Comment by felixonmars** [comment]
I don't have the problem here, but I have just bumped startdde to 3.1.24. Not sure if it will make a difference to you :(

**Comment by carlocastoldi** [comment]
yep! updating to 3.1.24 fixed it :D

**Comment by felixonmars** [comment]
That's great. Please re-open if you still get related problems.
