### ISSUE TITLE
Arch deepin-api-3.5.0-1 update issue

### ISSUE THREAD

**Issue by bishoptf** [linuxdeepin/dde-api#4]
Started seeing this a few days ago, and being lazy I assumed you were aware of the issue.  But the issue still exists so I thought I would pass it along.  I'm using Antergos an arch flavor and when performing a pkg update you receive an error on the deepin-api pkg, here is the output:

sudo pacman -Syu
[sudo] password....
:: Synchronizing package databases...
 antergos is up to date
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
error: could not open file /var/lib/pacman/local/deepin-api-3.5.0-1/desc: No such file or directory
resolving dependencies...
looking for conflicting packages...
warning: could not fully load metadata for package deepin-api-3.5.0-1
error: failed to prepare transaction (invalid or corrupted package)

Thanks :)

**Comment by BLumia** [comment]
Not sure but probably an issue of the mirror you're using. Switch to another mirror from `/etc/pacman.d/mirrorlist` and try `pacman -Syyu` again may helps.
